services:
  - type: web
    name: demo-merchant
    domains:
      - example.coinflow.cash
    runtime: static
    branch: main
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
